Add login-logout API
SPO-Career-Portal/SCP-Backend pull request #16
Opened 2021-06-10 06:49 UTC by sanchit-sinha

Added login logout API as per #12 
PS :Added  **_password_** and **_activated_** field in _**User**_ model

2021-06-11 08:18 UTC, namangup commented on requirements.txt
> +urllib3==1.26.5
We will manage dependencies in the end. Remove this for now.

2021-06-11 08:22 UTC, namangup commented on src/urls.py
> +urlpatterns = [path("admin/", admin.site.urls), path("auth/", include("user.urls"))]
Change this to `path("user/", include("user.urls"))`
Currently all URLs under user will be appended by `auth/`. That's not what we want.

2021-06-11 08:23 UTC, namangup commented on user/models.py
> +    password = models.CharField(max_length=300, null=True, blank=True)
Change max_length to 20

2021-06-11 08:25 UTC, namangup commented on user/urls.py
> +    path("logout/", views.Logout.as_view(), name="auth-logout"),
You can change these to `auth/login/` and `auth/logout/` respectively.

2021-06-11 08:26 UTC, namangup commented on user/views.py
> +from .utils import *
Bad coding practice. 
Instead of * specify what you need to import.

2021-06-11 08:27 UTC, namangup commented on user/models.py
>  class User(models.Model):
Add an email field here `email = models.CharField(max_length=100, unique=True)`

2021-06-11 08:28 UTC, namangup commented on user/views.py
> +        username = get_username(email)
user model already has a username field
The post request will have username instead of email. `get_username` is redundant, remove that.

2021-06-11 08:31 UTC, namangup requested changes
Make the required changes. Format again with black.

2021-06-11 08:56 UTC, sanchit-sinha commented on user/views.py
> +        username = get_username(email)
But, on the front-end side, we are logging in using our `email-ID` and `password`, so shall I make changes there as well ??

2021-06-11 13:11 UTC, namangup commented on user/views.py
> +        username = get_username(email)
Yes, authentication can be based on the username itself. During registration we can just have a check for iitk domain.

2021-06-11 18:25 UTC, sanchit-sinha commented
Made respective changes as per https://github.com/SPO-Career-Portal/SCP-Backend/pull/16#pullrequestreview-681583720

2021-06-12 09:20 UTC, namangup commented on user/models.py
> +from django.db.models.expressions import F
Where is this used?

2021-06-13 14:37 UTC, sanchit-sinha commented on user/models.py
> +from django.db.models.expressions import F
It was not used anywhere in that file.
I have removed that import.

2021-06-14 11:10 UTC, merged