API to fetch user data
SPO-Career-Portal/SCP-Backend pull request #17
Opened 2021-06-10 10:44 UTC by uditpd3000

2021-06-10 13:31 UTC, navneet-28 commented
closes #11

2021-06-11 08:32 UTC, namangup requested changes
Remove scripts folder. Format with black. Will review the code after that.

2021-06-11 10:44 UTC, uditpd3000 commented
closes #11

2021-06-11 13:08 UTC, namangup commented on user/apps.py
> -    default_auto_field = "django.db.models.BigAutoField"
Why is this removed?

2021-06-11 13:08 UTC, namangup commented on user/models.py
> +    roll = models.CharField(max_length=20, unique=True)
max_length 10 should be enough

2021-06-11 13:09 UTC, namangup commented on user/tests.py
> +from django.test import TestCase, Client
Any reason for these edits?

2021-06-11 13:14 UTC, namangup commented on user/serializers.py
> +class userserializer(serializers.ModelSerializer):
Class name should be title case `UserSerializer`

2021-06-11 15:08 UTC, uditpd3000 commented on user/tests.py
> +from django.test import TestCase, Client
No, actually in the initial stage of using Postman, I didn't know how to do tests so some mishappenings.

2021-06-11 15:09 UTC, uditpd3000 commented on user/serializers.py
> +class userserializer(serializers.ModelSerializer):
I have made all the suggested changes. Please revisit them.

2021-06-12 09:17 UTC, namangup commented on user/urls.py
> +app_name = "User"
Is this required? I think this can be removed

2021-06-12 09:18 UTC, namangup commented on user/utils.py
> +        return None
Include a check `if request.session.has_key("username"):` 
`else: return None`

2021-06-12 10:52 UTC, namangup commented
Resolve conflicts and add api documentation to README

2021-06-12 14:13 UTC, merged