Admin model and related APIs added
SPO-Career-Portal/SCP-Backend pull request #32
Opened 2021-07-15 13:45 UTC by parinayc20

@shashank1310 also contributed
There is a resume selection problem that needs to be fixed.

2021-07-15 14:04 UTC, namangup commented
Change parent directory name to `admin`
Update Readme (check if some previous api also needs to be updated)

2021-07-15 16:02 UTC, parinayc20 commented
The parent directory's name can't be changed to admin as it is conflicting with the django admin.

2021-07-15 18:47 UTC, namangup commented
In `src/urls.py` check if you can use the URL `admin` for `include(admins.urls)`. Remove the `admin` import from `django.contrib` since we anyway won't be using the django admin panel.

2021-07-16 12:51 UTC, parinayc20 commented
Model Finalized, Readme updated and the issue regarding `admin` resolved.

2021-07-16 14:00 UTC, namangup requested changes

2021-07-16 14:00 UTC, namangup commented on admins/views.py
> +
Implement authentication check.
Make it a class with a get function.

2021-07-16 14:00 UTC, namangup commented on admins/views.py
> +    try:
Same as above.

2021-07-16 15:42 UTC, parinayc20 commented
Made the requested changes.

2021-07-16 17:33 UTC, merged