added placement model
SPO-Career-Portal/SCP-Backend pull request #4
Opened 2021-05-31 17:58 UTC by Shubham63-hub

2021-06-01 05:35 UTC, Shubham63-hub commented
updated placement model, changed default of jsonfields to list from dict.

2021-06-01 09:00 UTC, shashank1310 commented
description ka max length  1500 kar de

2021-06-01 12:13 UTC, Shubham63-hub commented
done! increased the length of description and also changed timezone to  Asia/Calcutta

2021-06-04 15:14 UTC, SomTambe requested changes
Make the requested changes.

2021-06-04 15:14 UTC, SomTambe commented on .gitignore
> +db.sqlite3
Add a newline at the end of the file.

2021-06-04 15:14 UTC, SomTambe commented on placement/models.py
> +    eligible_batches = models.JSONField(default= list )
Change `eligible_batches = models.JSONField(default= list )` to `eligible_batches = models.JSONField(default=list)`. Notice the spaces and make the same changes for all the files.

2021-06-04 15:14 UTC, SomTambe commented on placement/models.py
> +    placement_text = models.CharField(max_length=300)
change the name from `placement_text` to `placement_name` or something similar.

2021-06-04 16:35 UTC, Shubham63-hub commented on placement/models.py
> +    placement_text = models.CharField(max_length=300)
changed placement_text to placement_name

2021-06-04 16:35 UTC, Shubham63-hub commented on placement/models.py
> +    eligible_batches = models.JSONField(default= list )
corrected the spaces

2021-06-04 16:36 UTC, Shubham63-hub commented on .gitignore
> +db.sqlite3
added a new line.

2021-06-05 12:55 UTC, closed without merging