added user model
SPO-Career-Portal/SCP-Backend pull request #5
Opened 2021-05-31 21:08 UTC by navneet-28

Added the user model. The resume2 link is set to be optional.

2021-06-01 09:16 UTC, navneet-28 commented
Updated the timezone and increased the max length for batch field.

2021-06-04 15:09 UTC, SomTambe commented on users/admin.py
> +admin.site.register(User)
Add a newline at the end of the file. I don't ever remember registering my models, I don't know if this is necessary.

2021-06-04 15:11 UTC, SomTambe requested changes
Make the requested changes.

2021-06-04 15:11 UTC, SomTambe commented on users/models.py
> +    mastercv=models.URLField(max_length=300,unique=True)
Make all the URL Fields of max length = `300`.

2021-06-04 16:05 UTC, navneet-28 commented
Made all the requested changes.

2021-06-05 12:56 UTC, closed without merging